### ISSUE TITLE
paid job

### ISSUE THREAD

**Issue by kodeine** [itninja-hue/aws-production-eks#2]
hello, please let me know if you're available for some paid work on devops.

thank you

**Comment by itninja-hue** [comment]
Hello, thank you for reaching out, yes. You can if you prefer email me more details, or suggest any other alternatives.

**Comment by kodeine** [comment]
> Hello, thank you for reaching out, yes. You can if you prefer email me more details, or suggest any other alternatives.

Hello, can you please email me at business@oblutu.com. This is a temporary email as this is a public platform. Once you email me ill send you another email

**Comment by itninja-hue** [comment]
> > Hello, thank you for reaching out, yes. You can if you prefer email me more details, or suggest any other alternatives.
> 
> Hello, can you please email me at [business@oblutu.com](mailto:business@oblutu.com). This is a temporary email as this is a public platform. Once you email me ill send you another email

Done, I ll close and delete issue once I get an email back from you
